name: Docs
on:
  push:
    branches:
      - main


jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    container: 'nimlang/nim:1.4.2-alpine'
    timeout-minutes: 10

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Install the dependencies'
        run: nimble install -dy

      - name: 'Build API doc'
        run: nimble docs

      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'nimble-build/docs'
