name: 'Tests'
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages


jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        # TODO: Add Nim 1.6.4 to the matrix once the Docker image is available.
        nim_version: ['1.4.2', '1.4.4', '1.4.6', '1.4.8', '1.6.0', '1.6.2']
        backend: ['c', 'cxx', 'objc', 'js']

    name: 'Unit tests: Nim ${{ matrix.nim_version }}, backend ${{ matrix.backend }}'
    runs-on: 'ubuntu-latest'
    container: 'nimlang/nim:${{ matrix.nim_version }}-alpine'
    timeout-minutes: 10

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup Objective-C'
        if: matrix.backend == 'objc'
        run: |
          apk add --no-cache gcc-objc
          mkdir -p "$HOME/.config/nim" && cp 'ci/tests/objc/nim.cfg' "$!"

      - name: 'Install the dependencies of the project'
        run: nimble install -dy

      - name: 'Build and run the tests'
        run: nimble test-${{ matrix.backend }}
