name: Tests
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages


jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        nim_version: ['1.4.2']
        backend: ['c', 'cxx', 'objc', 'js']

    name: 'Unit tests: Nim ${{ matrix.nim_version }}, backend ${{ matrix.backend }}'
    runs-on: ubuntu-latest
    container: 'nimlang/nim:${{ matrix.nim_version }}-alpine'
    timeout-minutes: 10

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup Objective-C'
        if: matrix.backend == 'objc'
        run: |
          apk add --no-cache gcc-objc
          mkdir -p ~/.config/nim
          echo 'gcc.objc.options.linker = "-lobjc"' > ~/.config/nim/nim.cfg

      - name: 'Install the dependencies of the project'
        run: nimble install -dy

      - name: 'Build and run the tests'
        run: nimble test-${{ matrix.backend }}
